//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MantenedorEstacionesDB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MantenedorEstacionesBDEntities : DbContext
    {
        public MantenedorEstacionesBDEntities()
            : base("name=MantenedorEstacionesBDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Estacion> Estacion { get; set; }
        public virtual DbSet<Punto> Punto { get; set; }
        public virtual DbSet<TipoPunto> TipoPunto { get; set; }
    }
}
